### ISSUE TITLE
中文 README 的 av 号是不是写错了？

### ISSUE THREAD

**Issue by windwq** [KrisCris/Palworld-Pal-Editor#10]
**Describe the bug**
<https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/README.cn.md>

**To Reproduce**

**Expected behavior**
<https://www.bilibili.com/video/av1001846154/>

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KrisCris** [comment]
坏了。。复制黏贴错了没发现

**Comment by KrisCris** [comment]
fixed: https://github.com/KrisCris/Palworld-Pal-Editor/commit/025166c32e28a77631a61d67d1f3e80f3fcc798b

**Comment by Mosney** [comment]
~~目前视频又没了~~

似乎是bilibili限制了来自GitHub的referer，直接点击链接会

> 啊叻？视频不见了？

手动复制粘贴av链接是可以正常打开的，贴一个bv链接试试能不能打开 

https://www.bilibili.com/video/BV1cx4y1D7we/
