### ISSUE TITLE
PW v0.2.0.6 ( Bellanoir + Variant can be added but not edited)

### ISSUE THREAD

**Issue by SentinelForce** [KrisCris/Palworld-Pal-Editor#13]
**Describe the bug**
New Raid Pal "Bellanoir" can be added via **"add pal"** but can't be edited if already caught.

**To Reproduce**
1. Open Save '...'
2. Scroll down to '....'
3. See error

**Expected behavior**
Bellanoir to appear in list for **BASE PAL** or **Player Name**

**Screenshots**
![Screenshot 2024-04-04 212833](https://github.com/KrisCris/Palworld-Pal-Editor/assets/13028408/9927af26-caec-4989-b038-a31bb4150ee8)
![Screenshot 2024-04asd212923](https://github.com/KrisCris/Palworld-Pal-Editor/assets/13028408/388db9d0-3161-4bc5-8eee-b12618bc7e07)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**

**Comment by KrisCris** [comment]
Can you confirm if 0.4.1 fixed this issue?

**Comment by SentinelForce** [comment]
@KrisCris - yep just checked and they show up in editor now

**Comment by KrisCris** [comment]
Awesome! Close as resolved.
