### ISSUE TITLE
Palworld-Pal-Editor 0.4.1.post2 on PyPi missing WebUI assets

### ISSUE THREAD

**Issue by imakin** [KrisCris/Palworld-Pal-Editor#14]
Hi Thank you for the application.

However the pip and the latest main branch version doesnt work. it shows error 404 page. 
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/6647566/06ffaafe-729f-4f4e-8c4e-b142c2f39402)

**how to reproduce**

        pip install palworld-pal-editor
        python -m palworld_pal_editor

i notice the the assets are placed in this folder `frontend/palworld-pal-editor-webui` ?
but that folder is not the one pointed by the `static_folder_path = Path(app.static_folder)` in webui.py

running the docker version also fails, got "The connection was reset" on the browser
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/6647566/e99c2d05-94d0-40c9-b350-459de2520e76)

docker/docker-compose.yml file:

        version: '3.8'
        services:
          palworld-pal-editor:
            image: docker.io/library/palworld-pal-editor
            container_name: palworld-pal-editor
            # network_mode: host
            ports:
              - 12345:12345
            environment:
              - TZ=UTC
              - PUID=1000
              - PGID=1000
              - APP_PORT=12345 # make sure this matches the port you are going to map
              - APP_LANG=en-US
              - MODE=web # [cli, web, gui] You are not going to run gui in docker though... ;)
              - SAVE_PATH=/mnt/gamesave
              - PASSWORD=password # remove this env unless you want a password, but password is strongly recommended (for web mode).
            volumes:
              - "/tmp:/mnt/gamesave"

**Comment by KrisCris** [comment]
Hmm, this is weird.

FYI, the WebUI is built and copied to the `app.static_folder` location

**Comment by KrisCris** [comment]
Can confirm this issue with the latest pypi published version.

Meanwhile, you can use the older version `pip install palworld-pal-editor==0.4.1`.

**Comment by KrisCris** [comment]
Fixed.

try `--upgrade` or `pip install palworld-pal-editor==0.4.1.post2`

**Comment by KrisCris** [comment]
As for the Docker, you will need to wait a while for the first launch before opening the webpage.
