### ISSUE TITLE
Player Delete

### ISSUE THREAD

**Issue by BloodDragon2580** [KrisCris/Palworld-Pal-Editor#17]
Good evening,
Can you add a feature that allows us to delete players and their bases?
That would be great.

**Comment by KrisCris** [comment]
Checkout this tool, it does exactly what you are looking for: https://github.com/magicbear/palworld-server-toolkit

**Comment by KrisCris** [comment]
Since this is a Pal editor, I don't expect player deletion to be implemented in the near future, especially there is an existing one ;)

**Comment by BloodDragon2580** [comment]
This dont work anymore. But thx for the answer.

**Comment by KrisCris** [comment]
> This dont work anymore. But thx for the answer.

Hmm that's kinda sad. Maybe you can check the forks of that project, and see if anyone updated it for the latest Palworld.

Player deletion isn't an easy task tho, a LOT of things have to be referenced and deleted lol
