### ISSUE TITLE
Modifying pal species does not update MaxFullStomach

### ISSUE THREAD

**Issue by stayli117** [KrisCris/Palworld-Pal-Editor#19]

**Comment by stayli117** [comment]
Penguin -> CatVampire

hope 150 -> 350 

However 150 -> 150

**Comment by KrisCris** [comment]
Well, I hope Palworld devs could fix it by themselves - just like what they did to the MaxHP. 

Unless someone makes a pull request, fetching and adding those values to the datasheet is a PITA.

**Comment by KrisCris** [comment]
Alternatively, I enabled interactive cli for both GUI and Web mode. (v0.6.0+)

You can try editing Pal's MaxFullStomach manually:

```python
pal = get_pal("your pal's id")
pal.MaxFullStomach = 350.0
```

**Comment by stayli117** [comment]
Thank you. Please enable this feature in the GUI, or tell me which file I need to configure these values in.

**Comment by KrisCris** [comment]
Just type in the terminal.

You can see the pal's ID on the GUI.

Then in the terminal, run the code above

**Comment by stayli117** [comment]
get！Thanks
