### ISSUE TITLE
Path not available when save the change.

### ISSUE THREAD

**Issue by FelixHenrikChristian** [KrisCris/Palworld-Pal-Editor#2]
**Describe the bug**
Successfully loaded my saves. I can see all my pals.
But when I changed the skills of my pal, the error occurred.
In the GUI, it says: writeSave - Error occured: Path not available?
In the terminal, it says: [WinError 3] 系统找不到指定的路径。

**To Reproduce**
1. Change any part of a pal.
2. Click on 'SAVE CHANGES'
3. See error

**Expected behavior**
It should work without error.

**Screenshots**
![1](https://github.com/KrisCris/Palworld-Pal-Editor/assets/103311931/4083c6b3-edd7-4f7b-bb00-a67bf62b0094)

**Desktop (please complete the following information):**
 - OS: Windows11 23H2
 - Version 23H2

**Additional context**
I'm not sure if it's my system's fault. But I've already enabled long path support. I've no idea how to fix that.

**Comment by KrisCris** [comment]
Can you provide the log file?
你能上传一下log文件吗，在logs文件夹里

**Comment by FelixHenrikChristian** [comment]
Sorry, I'm not sure if the editor on nexus is the latest version, I'm trying this latest version on github. This may work.
对不起，我下载的是nexus上面的版本，我不确定他是不是最新版，我试试下载github的最新版再尝试尝试。

**Comment by FelixHenrikChristian** [comment]
Still error😭 This is the log file:
[2024-03-04_20-39-30.log](https://github.com/KrisCris/Palworld-Pal-Editor/files/14481569/2024-03-04_20-39-30.log)

**Comment by KrisCris** [comment]
hmmm, I am unable to reproduce this error, but can you please test the latest build here: https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/8140618289

**Comment by FelixHenrikChristian** [comment]
This works!!!!  Thank you !!!!!!Love
💕💕💕

**Comment by KrisCris** [comment]
> This works!!!! Thank you !!!!!!Love 💕💕💕

Glad to hear this worked for you! I simply ignored all the unrelated files in the dir ; )

I do have the same `backup` folder in the save dir, not sure why this breaks on your end. But it's good that we are no longer backing these up.
