### ISSUE TITLE
Docker image (docker.io/library/palworld-pal-editor) not being found, I'm using Portainer

### ISSUE THREAD

**Issue by mizifih** [KrisCris/Palworld-Pal-Editor#26]
**Describe the bug**
Portainer, for some reason, can't find the image and `docker image pull docker.io/library/palworld-pal-editor` also not working. I believe I posted all the screenshots needed.

**Thank you for your time coding this project :)**

**To Reproduce**
All I did was add the composer information to the container creation form. If I try to pull the image using the terminal, it's also not working.

**Expected behavior**

**Screenshots**
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860837/5f76b717-4b3e-4468-8779-d8daa7225bea)
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860837/25e5b06e-8048-4c89-a489-183a372c725c)
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860837/065daf48-c95b-4962-9c8e-73bee60eacc3)
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860837/2ffc46bd-49c0-4a24-9440-c1075655fa68)
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860837/4afa825f-f24e-4897-9451-5497ae10175a)

**Headless Linux server:**
 - OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)
 - Portainer: Community Edition v2.19.4
 - Docker Engine - Community
  Engine:
  Version:          25.0.4
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       061aa95
  Built:            Wed Mar  6 16:32:12 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 - containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 - runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 - docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Additional context**
```
#sudo docker image pull docker.io/library/palworld-pal-editor
Using default tag: latest
Error response from daemon: pull access denied for palworld-pal-editor, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by KrisCris** [comment]
You need to clone and build the docker image, I didn’t upload it to the docker repository.

**Comment by KrisCris** [comment]
Can you try this:

`docker pull ghcr.io/kriscris/palworld-pal-editor:latest`

https://github.com/kriscris/Palworld-Pal-Editor/pkgs/container/palworld-pal-editor

**Comment by mizifih** [comment]
> Can you try this:
> 
> `docker pull ghcr.io/kriscris/palworld-pal-editor:latest`
> 
> https://github.com/kriscris/Palworld-Pal-Editor/pkgs/container/palworld-pal-editor

Oh yeah, gimme a few hours 'til I get home and I'll try for sure. Thank you for publishing the image.

**Comment by mizifih** [comment]
```
#docker pull ghcr.io/kriscris/palworld-pal-editor:latest
latest: Pulling from kriscris/palworld-pal-editor
13808c22b207: Already exists
6c9a484475c1: Pull complete
78bef5c7424f: Pull complete
42f0d54f5caa: Pull complete
1723cff2f16b: Pull complete
0085db0b9964: Pull complete
5d83258ff2b4: Pull complete
bd28324fec3b: Pull complete
108b344b48f6: Pull complete
b5d822708328: Pull complete
516798e92c98: Pull complete
646fe0bc1668: Pull complete
01a986f1a6e3: Pull complete
799fc25129f7: Pull complete
e439d0752f88: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:67602db4e910e3dc65ce5c6eb33b32351e530b46cb1ea88e0936773360ff912e
Status: Downloaded newer image for ghcr.io/kriscris/palworld-pal-editor:latest
ghcr.io/kriscris/palworld-pal-editor:latest
```

**Comment by mizifih** [comment]
Ok, I got lots of output when I built and ran the container, this is the very end:
```
Building wheels for collected packages: palworld-pal-editor
  Building editable for palworld-pal-editor (pyproject.toml) ... - done
  Created wheel for palworld-pal-editor: filename=palworld_pal_editor-0.8.0-0.editable-py3-none-any.whl size=30389 sha256=ee3cfcbea72ee6c84bed8b146ddbe1150106db7b5a1ae55adeaf4e550deddd60
  Stored in directory: /tmp/pip-ephem-wheel-cache-0_95pkjf/wheels/54/1b/b7/aa63e25c8f14f4f2ae7b04e6097bdecb770e455c5c1ee0a600
Successfully built palworld-pal-editor
Installing collected packages: palworld-pal-editor
Successfully installed palworld-pal-editor-0.8.0
Launching python -m palworld_pal_editor --nocli --lang=en --port=58888 --mode=web --path=/mnt/gamesave --password=0000...
2024-04-26 17:50:09 [INFO] Logs written to /app/src/palworld_pal_editor/logs
2024-04-26 17:50:09 [INFO] Config file written to /app/src/palworld_pal_editor/config.json
2024-04-26 17:50:09 [INFO] i18n: en, mode: web, port: 58888, path: /mnt/gamesave, password: 1670, JWT_SECRET_KEY: X2Nvbm5sb3N0
2024-04-26 17:50:09 [INFO] Running Palworld-Pal-Editor version: 0.8.0
2024-04-26 17:50:09 [INFO] LISTENING ON 0.0.0.0:58888.
```

But I can't access it, I tried using network as bridge, host, container (same as Palworld server), but it always says it's listening on `0.0.0.0:58888`.

**Processes list:**
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860837/5fcc74e7-cd8b-43c1-9a6c-f173fe7ebb9b)

**Comment by KrisCris** [comment]
Is this your remote server or local computer? If you were remote accessing the tool, make sure the port is correctly forwarded in your server/router settings.

The `APP_PORT` env controls which port the tool listens on.

This is the compose file you may want to look at: https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/docker/sample-docker-compose.yml

**Comment by mizifih** [comment]
It's a VM running Ubuntu Server, with Docker and Portainer running on Proxmox. But it's all OK now, even though it's still showing that zero IP, I can access it normally. And I did nothing different, just gave it another try. I guess it was just computer doing bad computer stuff.

**Comment by KrisCris** [comment]
> even though it's still showing that zero IP

Yeah, this is the address:port the tool binds to, which means it binds to all network interfaces iirc.

Btw, I forgot to mention that its first launch actually takes longer.

**Comment by KrisCris** [comment]
OK, I just fixed a bug that prevents Sheepball's icon from being loaded and refined the docker file.

Can you test if, in this version, the editor starts to work soon after the container is created? 

`docker pull ghcr.io/kriscris/palworld-pal-editor:latest`

**Comment by mizifih** [comment]
Pretty much instantly after `Launching python -m palworld_pal_editor --nocli --lang=en --port=58888 --mode=web --path=/mnt/gamesave --password=SomethingSecure-Sorta...` appeared at the log.
