### ISSUE TITLE
Not working in Linux dedicated headless environment

### ISSUE THREAD

**Issue by sebagallo** [KrisCris/Palworld-Pal-Editor#3]
Using docker-compose method in linux headless environment

```
palworld-editor  | Installing collected packages: darkdetect, customtkinter, palworld-pal-editor
palworld-editor  | Successfully installed customtkinter-5.2.2 darkdetect-0.8.0 palworld-pal-editor-0.2.1
palworld-editor  | Running command: python -i -m palworld_pal_editor --mode "web" --lang "en-US" --port "12345" --path "/mnt/gamesave" --password ""
palworld-editor  | 2024-03-04 14:42:11 [INFO] Logs written to /app/src/palworld_pal_editor/logs
**palworld-editor  | /app/src/palworld_pal_editor/cli.py:113: SyntaxWarning: invalid escape sequence '\g'**
palworld-editor  |   """
palworld-editor  | 2024-03-04 14:42:11 [ERROR] Exception caught on __main__: Object of type property is not JSON serializable
palworld-editor  | >>> 
```

I guess this happens because inside that logger.info method, the string contains at the last line \g
after removing it, **palworld-editor  | /app/src/palworld_pal_editor/cli.py:113: SyntaxWarning: invalid escape sequence '\g'** disappears.

BUT I still get the 
**palworld-editor  | 2024-03-04 14:42:11 [ERROR] Exception caught on __main__: Object of type property is not JSON serializable**
right after the info message.

**Comment by KrisCris** [comment]
Can you pull the latest changes and post the log?

**Comment by sebagallo** [comment]
While you were working on it, I managed to make it work now by myself. I think it was probably a lack of config.json and/or not passing the password env var? well, one of the two, cant be arsed to go back at testing this.

Also not passing the password actually passes it as 'null', and the frontend will require it.

**Comment by KrisCris** [comment]
Alright, thanks for letting me know! I think I've fixed it.
