### ISSUE TITLE
Can't pick save folder?

### ISSUE THREAD

**Issue by miabi81** [KrisCris/Palworld-Pal-Editor#31]
**Describe the bug**
I downloaded the Pal Editor and have directed the address to the folder where the save is, but the OK is greyed out and it won't let me confirm it or pick it. Is there something I'm missing?

**Comment by KrisCris** [comment]
Please post a screenshot of the tool

**Comment by miabi81** [comment]
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/173857514/b1ecd23c-786b-4862-b930-4b084b4b9420)

**Comment by KrisCris** [comment]
Ah, so you are playing on a server? You will have to modify the save file on the server then. (Data is stored in Level.sav)

**Comment by miabi81** [comment]
Multiplayer game so not quite a server but would guess same situation?

**Comment by KrisCris** [comment]
> Multiplayer game so not quite a server but would guess same situation?

Yep, only the host has the full game save.
