### ISSUE TITLE
Update & translation

### ISSUE THREAD

**Issue by Mboubou1** [KrisCris/Palworld-Pal-Editor#34]
Hey

with the new update of the game can you update your save editor ?

thanks in advance

**Comment by KrisCris** [comment]
There will be an update SOON™️

**Comment by Mboubou1** [comment]
Great 

Btw 
I am available if you want to do French translations

**Comment by KrisCris** [comment]
Thank you for your interest! But I am not sure how much you want to contribute, cuz there are quite a lot of texts.

For the UI: https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/frontend/palworld-pal-editor-webui/src/i18n/en.js

For the Pal & Skills: 
- https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/src/palworld_pal_editor/assets/data/pal_data.json
- https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/src/palworld_pal_editor/assets/data/pal_attacks.json
- https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/src/palworld_pal_editor/assets/data/pal_passives.json

**Comment by Mboubou1** [comment]
Okay, I’ll translate the files after how do you want me to give them to you?

**Comment by KrisCris** [comment]
You can open a pull request.
