### ISSUE TITLE
Game Performance Drops off a Cliff

### ISSUE THREAD

**Issue by LordOfTheWeebs** [KrisCris/Palworld-Pal-Editor#35]
**Describe the bug**
In short, after using the program, the game's performance has declined considerably, almost to a point of unplayability at random. Specifically, when loading into the world, it will freeze for a good 5-10 seconds after the terrain starts to load. When returning to the title screen, the game will again freeze, but for anywhere from 30 seconds to 5 minutes if it doesn't decide to completely hang.

Recently, after the update and after duping three of my pals 20 times each to take on Blazamut Ryu, I've started to experience the occasional crash either upon X'ing out of the patch notes upon bootup, upon attempting to load my world, attempting to return to title, and both times after opening the palbox after acquiring Blazamut Ryu from the new raid (both in party and in box, one each time). When it crashes, the state of my save will be completely random in how much is saved. Sometimes everything is reverted to the last autosave/full save, sometimes my items are still there but my pal party is different, sometimes all my items will be gone but I'll be in the same location as when the crash occurred, etc. (ex: first time I beat Blazamut Ryu at a secondary base, I went to open my palbox to store him and the game crashed. My new location was saved, but Blazamut Ryu and all the drops were missing, _except_ for the coal, stone, and paldium fragments from destroyed rocks at the site of the battle)

I **_did_** create a brand new world to try out on to see if any of those issues sans the crashing remained, and they didn't, so I'm unsure if this is due to the editor or something going on with the world data corrupting over time from its age and updates changing things.

**To Reproduce**
I'm honestly unsure of the steps to reproduce the issue, since using the editor the first time began introducing the issues of slowdown and hanging, which have gotten worse over time.

**Expected behavior**
No changes to performance.

**Screenshots**
Due to the nature of the issue, I do not have bugs, and since only one specific circumstance appears to be reliably reproducible, I can't really provide any evidence except for the main issue, which I have a short video of [here](https://www.youtube.com/watch?v=Et8r1rKv36c)

**System (please complete the following information):**
 - OS: Nobara Linux 39
 - Steam version of Palworld, using proton versions 8 and 9, with and without the launch options of gamemoderun, mangohud, and -dx12
 - Editor Version: Python installed 0.8.0

**Additional context**
I'm honestly not sure if this is related to the editor, but it seems mostly independent of updates (major and minor), proton versions, and launch options, so I'm going to take a guess and report it anyway, just in case this is a known/unknown issue that indeed involves the editor.

I hope this explains everything that might be relevant

**Comment by KrisCris** [comment]
Are you using any mods? And do you have this issue before the update?

Can you provide the editor's log file and your gamesave? And if your game has crashed, you can also provide that log. 

Tbh I don't believe this is related to my tool, this game is never stable, lol. But I will try look into it.

**Comment by LordOfTheWeebs** [comment]
I used the Ore Crusher and Rich Businessman mods before the update, but removed them before the update since I never wound up using them.

To provide the most complete picture, [here](https://drive.google.com/file/d/1wPsZrdM7_4Y_ckACHXki1i7WVvQJbpON/view?usp=drive_link) are all the editor log files I have, my total save, and the crashes that I experienced.

**Comment by LordOfTheWeebs** [comment]
Yeah this can be closed, turns out the issue was the dwmapi.dll from the UE4SS causing all of the problems, [found the solution on Reddit](https://www.reddit.com/r/Palworld/comments/1act66r/comment/kpqtspe).

**Comment by LordOfTheWeebs** [comment]
Yeah this can be closed, turns out the issue was the dwmapi.dll from the UE4SS causing all of the problems, [found the solution on Reddit](https://www.reddit.com/r/Palworld/comments/1act66r/comment/kpqtspe).
