### ISSUE TITLE
Feature: add 0.3.2 new passive skill **Nocturnal** to let non-dark pal work at night

### ISSUE THREAD

**Issue by Mosney** [KrisCris/Palworld-Pal-Editor#36]
I downloaded latest [GitHub action version](https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/9742718662) and there no this passive skill can be choose.

**Comment by Mosney** [comment]
It seems not only this missing, many new content still WIP.

Anyway thanks to the author for his selfless efforts to bring us a handy tool!

**Comment by KrisCris** [comment]
Fixed in the latest update. If you found anything missing, do let me know.
