### ISSUE TITLE
Error loading save

### ISSUE THREAD

**Issue by Matteoz991** [KrisCris/Palworld-Pal-Editor#38]
**Describe the bug**
fails to open a save file

**To Reproduce**
unzip [830A93F34E74CB7629063CB72BACEA72.zip](https://github.com/user-attachments/files/16132158/830A93F34E74CB7629063CB72BACEA72.zip)
if you try to load it you get this error:
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/37067366/d770155f-437d-49bb-8be6-7a94c5290c60)

running this windows build on windows 11
https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/9838584931/artifacts/1677320828
from this commit 
https://github.com/KrisCris/Palworld-Pal-Editor/commit/897f205b73ffed55f18496ed21cd78970fb4894a
currently the latest build

**Comment by KrisCris** [comment]
You will have to use the build released here
https://github.com/KrisCris/Palworld-Pal-Editor/releases/tag/sakurajima_pre1

**Comment by KrisCris** [comment]
Since palworld_save_tools has been updated, https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/9848212374 should also work

**Comment by Matteoz991** [comment]
It works. Thanks <3
