### ISSUE TITLE
GUI (PyWebView) not working on certain platform

### ISSUE THREAD

**Issue by BloodDragon2580** [KrisCris/Palworld-Pal-Editor#4]
When I start the program, no image is displayed on my Windows 2019 Server, see photo.

![Screenshot 2024-03-04 150439](https://github.com/KrisCris/Palworld-Pal-Editor/assets/1429236/c79002f8-5270-41b9-b156-c4cbf410630a)

**Comment by KrisCris** [comment]
Update Aug 8, 2026: You are now able to connect to your running editor backend via the official web UI frontend: https://kriscris.github.io/Palworld-Pal-Editor/

Caveat: You need to enable password protection before using this feature.

<img width="3819" height="1969" alt="Image" src="https://github.com/user-attachments/assets/445910f3-1607-4619-a1b0-451a6c84e1c4" />

----

**Update:** 

If you don't like opening the browser or installing whatever runtime it requires, then try this build: https://github.com/KrisCris/Palworld-Pal-Editor/releases/tag/Alt-QtWebView

----

open `http://127.0.0.1:58080` (or whatever port you specified) in your browser, preferably Firefox or Chrome.

or, try running with `--mode web`, or set "mode": "web" in the generated config

Note: if you run the program in web mode while having an open firewall rule for the port, you may want to set a password, see the Config section on the readme ; )

**Comment by KrisCris** [comment]
**For Windows User:** To fix this, you will need to install the MS Edge Runtime: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Further detail: https://pywebview.flowrl.com/guide/web_engine.html
