### ISSUE TITLE
Docker Image Not Updated for Sakurajima Update

### ISSUE THREAD

**Issue by mizifih** [KrisCris/Palworld-Pal-Editor#41]
Is the docker image "ghcr.io/kriscris/palworld-pal-editor:latest" ready to support the Sakurajima Update? I saw that you have releases ready for this, but looks like my docker image wont update, when I pull it says I have the latest version and it doesn't seem to work with my save anymore.

**Comment by KrisCris** [comment]
Try if it works for you now
