### ISSUE TITLE
[Game Outdated] Latest version does not display pals list

### ISSUE THREAD

**Issue by stayli117** [KrisCris/Palworld-Pal-Editor#42]
[Saved.zip](https://github.com/user-attachments/files/16171981/Saved.zip)

**Comment by stayli117** [comment]
config.json = `{
    "i18n": "zh-CN",
    "mode": "gui",
    "port": 58080,
    "path": "/Users/stayli117/Downloads/Saved/SaveGames/0/93DD245D4070D02BA94ED4A76AAD4BA6",
    "password": null,
    "JWT_SECRET_KEY": "X2Nvbm5sb3N0"
}`

**Comment by stayli117** [comment]
this commit "853964890f2d5a477b45ccb2a6c2c87a0bbb6106" is work

**Comment by KrisCris** [comment]
Are you running the updated game? If not, use the old editor. Or you will have to enable "Show Ghost Pal"

**Comment by KrisCris** [comment]
After examining your save, it's likely that you are running an outdated Palworld, which is not supported by the updated editor.
