### ISSUE TITLE
[BUG] load Save-Error occured: Unknown Type: UInt32Property

### ISSUE THREAD

**Issue by PB-Star** [KrisCris/Palworld-Pal-Editor#46]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [ ] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

"load Save-Error occured: undefined" is displayed when reading the archive.
An error was displayed when I asked it to read my archive,BUT it can read another archive.

### Expected Behaviour

load Save

### Editor Version

0.9.0

### Game Version

0.3.3

### Logs

![Snipaste_2024-07-13_01-36-12](https://github.com/user-attachments/assets/d135b6d0-ad61-470e-99ce-a187d69c0fa9)
![Snipaste_2024-07-13_02-03-04](https://github.com/user-attachments/assets/6741a99f-0143-4804-95c3-5a6eb1a4209f)

**Comment by KrisCris** [comment]
Can you provide the full log (the file)

**Comment by PB-Star** [comment]
![Snipaste_2024-07-13_12-36-41](https://github.com/user-attachments/assets/ea48bdd6-9ff5-4be3-a308-24785b41b806)

**Comment by KrisCris** [comment]
Can you confirm that you are running the latest editor? The UInt32Property should have already been fixed since day 1

**Comment by PB-Star** [comment]
Oh,sorry,the problem was fixed it when I updated the editor. Thank you very much for your reply!(●'◡'●)
