### ISSUE TITLE
Level.sav No Longer Exists to Use the Application With

### ISSUE THREAD

**Issue by LordOfTheWeebs** [KrisCris/Palworld-Pal-Editor#49]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [X] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

Attempting to use the application no longer works because the Level.sav file no longer exists, only LevelMeta.sav and WorldOption.sav. I'm unsure if this is an issue that the editor needs to adjust for or if I accidentally changed a setting in Palworld that changes the save format.

![Screenshot_20240713_205956](https://github.com/user-attachments/assets/5fd06fd6-1d65-45ab-ae66-e5f01a6c119b)

### Expected Behaviour

Accessing the save file

### Editor Version

0.9.0 QWebEngineView (happened with pip installation as well)

### Game Version

0.3.3.55731

### Logs

[2024-07-13_20-59-43.log](https://github.com/user-attachments/files/16213571/2024-07-13_20-59-43.log)

### Your Game Save

[C75B46F44BEC2A855E3AD7B9D0D38D3F.tar.gz](https://github.com/user-attachments/files/16213725/C75B46F44BEC2A855E3AD7B9D0D38D3F.tar.gz)

**Comment by KrisCris** [comment]
bc you are playing on a game session hosted by someone else. You can only edit game saves that you own.

**Comment by LordOfTheWeebs** [comment]
This is my world that I made when I first played the game, the same world I've been using the editor on previously. The only things I can think of that might've messed with it are that I disabled and re-enabled multiplayer mode, disabled and re-enabled cloud saves, and deleted backups that were glitched/borked. Aside from that, this is the same uninterrupted singleplayer world I created in like February.

**Comment by LordOfTheWeebs** [comment]
Yeah this can be ignored. A dead save was in my home directory, my actual save is stored in a different drive where I had Palworld downloaded to. I forgot I changed the location for Palworld's actual install between drives to test some things.
