### ISSUE TITLE
[FEATURE REQUEST] Nocturnal Trait

### ISSUE THREAD

**Issue by xialouis** [KrisCris/Palworld-Pal-Editor#52]
### Please confirm

- [X] I have searched existing feature requests
- [X] This feature is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

### Feature Description

Can the new Nocturnal trait be added to the passives list?

### Expected Benefits

Allow pal editor's passive list to include Nocturnal

### Editor Version

0.9.0

### Game Version

0.3.5.57064

**Comment by KrisCris** [comment]
This skill should have already been added to the editor... Are you using the latest editor?
