### ISSUE TITLE
[FEATURE REQUEST] <title>9月17日更新后无法载入存档

### ISSUE THREAD

**Issue by SORAPSYGA** [KrisCris/Palworld-Pal-Editor#55]
### Please confirm

- [ ] I have searched existing feature requests
- [ ] This feature is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [ ] I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

### Feature Description

9月17日游戏更新后，无法载入最新版本的存档

### Expected Benefits

能否追加一个白天模式的背景设置

### Editor Version

0.9.0

### Game Version

0.3.7

**Comment by KrisCris** [comment]
Thanks for the report! Please bring further discussion to https://github.com/KrisCris/Palworld-Pal-Editor/issues/57. Also, it would be helpful if you could upload me a gamesave.
