### ISSUE TITLE
[BUG] <title> Unable to load Pal enhanced by Statue of Power

### ISSUE THREAD

**Issue by backno123** [KrisCris/Palworld-Pal-Editor#64]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [x] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

Version 0.10.0 was unable to load Pal's that were enhanced by Statue of Power, when I reset those enhanced Pal's in the statue in the game, the tool loaded properly. To be precise, the tool is able to read the existence of these pal, but cannot load their detail pages or modify them.

### Expected Behaviour

The tool should be able to successfully load the Pal enhanced by Statue of Power

### Editor Version

0.10.0

### Game Version

0.3.9

### Logs

2024-10-08 16:22:08 [INFO] Get backno's pal: 暗巫猫♂ - backno - 1f80975e-4782-b9c4-e2d2-1294b8bd64e9
ERROR:palworld_pal_editor.webui:Exception on /api/pal/paldata [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\pal.py", line 77, in paldata
  File "palworld_pal_editor\api\pal.py", line 113, in _pal_data
  File "palworld_pal_editor\core\pal_entity.py", line 501, in ComputedAttack
TypeError: unsupported operand type(s) for *: 'dict' and 'float'

**Comment by KrisCris** [comment]
Thanks for the feedback, can you provide me your gamesave?

**Comment by backno123** [comment]
[Level.zip](https://github.com/user-attachments/files/17290582/Level.zip)

**Comment by backno123** [comment]
My full archive file exceeded the size limit, so I uploaded it to a web drive
https://1drv.ms/u/c/7c9ce9e2fcd5ed2a/ERkIFQF3OOhBpB5lv21_eMcBAedgn-vQNVWUGlK-fmrZnQ?e=Lv5ohP

**Comment by KrisCris** [comment]
https://github.com/KrisCris/Palworld-Pal-Editor/releases/tag/v0.10.1 See if this build fix the issue.

**Comment by backno123** [comment]
Problem solved, thank you very much
