### ISSUE TITLE
[BUG] <title>治愈所有帕鲁的功能使用会报错

### ISSUE THREAD

**Issue by SORAPSYGA** [KrisCris/Palworld-Pal-Editor#65]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [X] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

使用治愈功能会报错然后停止继续执行

### Expected Behaviour

看上去像是我这只帕鲁数据有问题导致的停止执行，换了一个上周的存档也是一样的错误，更旧的存档因为都删了没法测试

### Editor Version

0.10.0

### Game Version

0.3.9

### Logs

![image](https://github.com/user-attachments/assets/e645958c-9ef8-44e4-aecd-c22b06641c62)

### Your Game Save

[Level.zip](https://github.com/user-attachments/files/17327581/Level.zip)

**Comment by KrisCris** [comment]
See if this build fix the issue: https://github.com/KrisCris/Palworld-Pal-Editor/releases/tag/v0.10.1

**Comment by SORAPSYGA** [comment]
> See if this build fix the issue: https://github.com/KrisCris/Palworld-Pal-Editor/releases/tag/v0.10.1

The issue has been resolved. Thank you very much!
