### ISSUE TITLE
服务器设置后不生效

### ISSUE THREAD

**Issue by Ericjankes** [KrisCris/Palworld-Pal-Editor#70]
### Please confirm

- [X] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [ ] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

 服务器点击治愈所有帕鲁不生效   其他功能也不生效，我已管理员运行

### Expected Behaviour

。。

### Editor Version

。。

### Game Version

。。

### Logs

。。

**Comment by KrisCris** [comment]
log？
