### ISSUE TITLE
[FEATURE REQUEST]  Allow Users to Translate the Tool

### ISSUE THREAD

**Issue by FelpsDeveloper3001** [KrisCris/Palworld-Pal-Editor#71]
### Please confirm

- [x] I have searched existing feature requests
- [x] This feature is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

### Feature Description

Enable users to contribute translations for your tool, making it easier to add new languages. This approach broadens your system's reach and engages the community.

### Expected Benefits

Broader Accessibility: Expands the tool's usability to a global audience by supporting more languages.
Community Engagement: Encourages user participation, fostering a sense of ownership and collaboration.
Cost Efficiency: Reduces the need for professional translation services by leveraging user contributions.
Faster Language Expansion: Speeds up the process of adding new languages through community-driven efforts.
Improved Localization Quality: Ensures translations are culturally relevant and accurate, as they come from native speakers or fluent users.

### Editor Version

0.10.1

### Game Version

0.3.10

**Comment by KrisCris** [comment]
Thanks for your suggestion, but currently I have no plan to use 3rd party platforms to do the i18n stuff. You can already translate the tool, there are files for different languages. All you need to do is to fork the project, contribute to the i18n, and then open a pull request ;)
