### ISSUE TITLE
[FEATURE REQUEST] <title>有办法增加主动技能槽吗

### ISSUE THREAD

**Issue by miaomiao-222438** [KrisCris/Palworld-Pal-Editor#77]
### Please confirm

- [X] I have searched existing feature requests
- [X] This feature is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

### Feature Description

有办法可以增加主动技能槽吗

### Expected Benefits

我以前改的，这只宠物可以释放十几个主动技能。但是现在不会改了。
![Snipaste_2024-12-25_23-07-40](https://github.com/user-attachments/assets/d4e7b4a3-5418-42fd-86a1-951771ab84d9)

### Editor Version

0.8.1

### Game Version

0.3.3

**Comment by KrisCris** [comment]
Added in 0.11.0 Preview 02

Disabling the **Hide Invalid Options** button will allow you to add more than 3 skills to the pal.
