### ISSUE TITLE
[FEATURE REQUEST] <title>添加天坠版本的帕鲁和帕鲁被动技能

### ISSUE THREAD

**Issue by shuimuzhixia** [KrisCris/Palworld-Pal-Editor#79]
### Please confirm

- [X] I have searched existing feature requests
- [X] This feature is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

### Feature Description

没有最新版的帕鲁和帕鲁被动技能。希望添加。

### Expected Benefits

增加天坠版本的帕鲁和帕鲁被动技能。

### Editor Version

0.11.0

### Game Version

0.4.11

**Comment by KrisCris** [comment]
duplicated https://github.com/KrisCris/Palworld-Pal-Editor/issues/73
