### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by teny1989** [KrisCris/Palworld-Pal-Editor#8]
I've installed the latest python, my save file is correctly entered in the config, I've tried running the .exe as administrator, I've tried running the port it was set to in Chrome, tried setting a password, tried forwarding the port it was set to. Just a blank screen.

I'm using Windows 10, latest version of the editor, latest python 3.12.2

**Comment by KrisCris** [comment]
can you provide a screenshot of the terminal, or preferably the log file?

**Comment by KrisCris** [comment]
FYI, you don't need Python installed to run the .exe version.

Might be the same issue: https://github.com/KrisCris/Palworld-Pal-Editor/issues/4

Close as inactive.

**Comment by PaleNeutron** [comment]
![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/8296331/68e58885-14b7-4bab-acd1-6ba20e584558)

Latest release, it seems `sw.js` is served with text mine, which prevent browser from executing it.

**Comment by KrisCris** [comment]
> ![image](https://private-user-images.githubusercontent.com/8296331/319485898-68e58885-14b7-4bab-acd1-6ba20e584558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTY1MzIsIm5iZiI6MTcxMjIxNjIzMiwicGF0aCI6Ii84Mjk2MzMxLzMxOTQ4NTg5OC02OGU1ODg4NS0xNGI3LTRiYWItYWNkMS02YmEyMGU1ODQ1NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDczNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU3NzYwMTkxODMxOGJjNzIyZTA4MGIxMjdkYzJhYjZlNDlhNDk4NmZkNTlmM2RhNWU0ZWU1NWFkMmU5NTBlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kUgZ6sbFoRZrZwDY0iFn3Ieg38hKrhowCjPAccbBKQU)
> 
> Latest release, it seems `sw.js` is served with text mine, which prevent browser from executing it.

Does force refresh (hold shift and refresh) the page help?

Update:

I removed the PWA support in the latest commit since it has no real use cases.

**Comment by PaleNeutron** [comment]
> Does force refresh (hold shift and refresh) the page help?

No, I have tried Ctrl+Shift+R and check disable cache in dev tools.

**Comment by KrisCris** [comment]
Can you confirm if the latest commit [d8282c3](https://github.com/KrisCris/Palworld-Pal-Editor/commit/d8282c35a0ce092fa910565c6b6e8c00eae5b6d0) fixed the issue? FYI I couldn't reproduce it on my end.

**Comment by KrisCris** [comment]
> No, I have tried Ctrl+Shift+R and check disable cache in dev tools.

FYI MIME Type issue has been fixed: https://github.com/KrisCris/Palworld-Pal-Editor/issues/15
