### ISSUE TITLE
[FEATURE REQUEST] <title> Please Add the new Passive traits 

### ISSUE THREAD

**Issue by Adarsh49-Gengaar** [KrisCris/Palworld-Pal-Editor#80]
### Please confirm

- [X] I have searched existing feature requests
- [X] This feature is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

### Feature Description

With the feybreak update to palworld new passive traits are added to the game - (https://paldb.cc/en/Passive_Skills), So please can you add the new traits in the editor.

### Expected Benefits

This will make new traits available in the editor.

### Editor Version

0.11.0 preview 2

### Game Version

0.4.12

**Comment by KrisCris** [comment]
duplicated https://github.com/KrisCris/Palworld-Pal-Editor/issues/73
